
variables:
  VERSION: 1.0.$CI_PIPELINE_ID
  EVENT_BUS_CLIENT_VERSION: 1.0.113


stages:
  - get_dependencies
  - test
  - build
  - release

fetch_client_lib:
  stage: get_dependencies
  image: curl
  script:
    - "curl -f -L -H \"PRIVATE-TOKEN: ${SECRET_APIKEY}\" -o include/foo.pdf 'https://sed-team-project/SED-DEV-group/event-bus-client-lib/builds/artifacts/patrick_modifications/target/eventbusclient-$EVENT_BUS_CLIENT_VERSION.jar?job=build'"

test:
  stage: test
  image: maven:3-jdk-8
  script:
    - mvn test

build:
  stage: build
  image: maven:3-jdk-8
  script:
    - mvn versions:set -DnewVersion=$VERSION
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
